services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver:/opt/geoserver_data
    networks:
      - demo_app
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - dbLoginData:/var/lib/postgresql/data
    networks:
      - demo_app
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - demo_app
  api:
    build: api
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    command: ["npm", "run", "dev:debug"]
    networks:
      - demo_app
  app:
    build: app
    ports:
      - "3001:3001"
    stdin_open: true
    volumes:
      - ./app/src:/usr/src/app/src
    networks:
      - demo_app
  web-map:
    build: web-map
    ports:
      - "4200:4200"
    volumes:
      - ./web-map:/usr/web-map
    networks:
      - demo_app

volumes:
  dbLoginData:
    driver: local
  cache:
    driver: local

networks:
  demo_app:
    driver: bridge