services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - dbLoginData:/var/lib/postgresql/data
  api:
    build: api
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    command: ["npm", "run", "dev:debug"]
  app:
    build: app
    ports:
      - "3001:3000"
    volumes:
      - ./app/src:/usr/src/app/src
volumes:
  dbLoginData:
    driver: local